--- # Connection
- name: Install Wordpress
  hosts: all
  become: true
  become_method: sudo
  user: ec2-user
  vars:
    wordpress_version: "4.0.32"
    php_version: "5.4.16"
  tasks:
  - name: Install httpd and prerequisites
    when: ( ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "CentOS" )
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - httpd
    - php-{{ php_version }}
    - php-mysql-{{ php_version }}
    - wget
    