--- # Connection
# ansible-playbook user.yaml
- name: Install instances
  hosts: localhost
  become: true
  become_method: sudo
  user: ec2-user
  tasks:
  - amazon.aws.ec2:
    key_name: laptop
    instance_type: t2.micro
    image: ami-074cce78125f09d61
    wait: yes
    group: webserver
    count: 5
    